//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eChartProject.Web.App_GlobalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Global {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Global() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("eChartProject.Web.App_GlobalResources.Global", typeof(Global).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  *.
        /// </summary>
        internal static string Common_Asterisk {
            get {
                return ResourceManager.GetString("Common_Asterisk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log out.
        /// </summary>
        internal static string Common_Button_Logout {
            get {
                return ResourceManager.GetString("Common_Button_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me.
        /// </summary>
        internal static string Common_Checkbox_RememberMe {
            get {
                return ResourceManager.GetString("Common_Checkbox_RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to :.
        /// </summary>
        internal static string Common_Colon {
            get {
                return ResourceManager.GetString("Common_Colon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2011 www.esuperfund.com.au.
        /// </summary>
        internal static string Common_Footer_Copyright {
            get {
                return ResourceManager.GetString("Common_Footer_Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Common_Form_Password {
            get {
                return ResourceManager.GetString("Common_Form_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Username.
        /// </summary>
        internal static string Common_Form_Username {
            get {
                return ResourceManager.GetString("Common_Form_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The passwords do not match..
        /// </summary>
        internal static string Common_Message_Compare_Password {
            get {
                return ResourceManager.GetString("Common_Message_Compare_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Age is invalid..
        /// </summary>
        internal static string Common_Message_ExpressionError_Age {
            get {
                return ResourceManager.GetString("Common_Message_ExpressionError_Age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The City is invalid..
        /// </summary>
        internal static string Common_Message_ExpressionError_City {
            get {
                return ResourceManager.GetString("Common_Message_ExpressionError_City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Country is invalid..
        /// </summary>
        internal static string Common_Message_ExpressionError_Country {
            get {
                return ResourceManager.GetString("Common_Message_ExpressionError_Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email is invalid..
        /// </summary>
        internal static string Common_Message_ExpressionError_Email {
            get {
                return ResourceManager.GetString("Common_Message_ExpressionError_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password is invalid..
        /// </summary>
        internal static string Common_Message_ExpressionError_Password {
            get {
                return ResourceManager.GetString("Common_Message_ExpressionError_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user name is invalid..
        /// </summary>
        internal static string Common_Message_ExpressionError_Username {
            get {
                return ResourceManager.GetString("Common_Message_ExpressionError_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The age is too long..
        /// </summary>
        internal static string Common_Message_ExpressionLong_Age {
            get {
                return ResourceManager.GetString("Common_Message_ExpressionLong_Age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The city is too long..
        /// </summary>
        internal static string Common_Message_ExpressionLong_City {
            get {
                return ResourceManager.GetString("Common_Message_ExpressionLong_City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The country is too long..
        /// </summary>
        internal static string Common_Message_ExpressionLong_Country {
            get {
                return ResourceManager.GetString("Common_Message_ExpressionLong_Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email is too long..
        /// </summary>
        internal static string Common_Message_ExpressionLong_Email {
            get {
                return ResourceManager.GetString("Common_Message_ExpressionLong_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user name is too long..
        /// </summary>
        internal static string Common_Message_ExpressionLong_UserName {
            get {
                return ResourceManager.GetString("Common_Message_ExpressionLong_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The age field can not be empty..
        /// </summary>
        internal static string Common_Message_FieldEmpty_Age {
            get {
                return ResourceManager.GetString("Common_Message_FieldEmpty_Age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The city field can not be empty..
        /// </summary>
        internal static string Common_Message_FieldEmpty_City {
            get {
                return ResourceManager.GetString("Common_Message_FieldEmpty_City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The confirm password field can not be empty..
        /// </summary>
        internal static string Common_Message_FieldEmpty_ConfirmPassword {
            get {
                return ResourceManager.GetString("Common_Message_FieldEmpty_ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The country field can not be empty..
        /// </summary>
        internal static string Common_Message_FieldEmpty_Country {
            get {
                return ResourceManager.GetString("Common_Message_FieldEmpty_Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email field can not be empty..
        /// </summary>
        internal static string Common_Message_FieldEmpty_Email {
            get {
                return ResourceManager.GetString("Common_Message_FieldEmpty_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password field can not be empty..
        /// </summary>
        internal static string Common_Message_FieldEmpty_Password {
            get {
                return ResourceManager.GetString("Common_Message_FieldEmpty_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The username field can not be empty..
        /// </summary>
        internal static string Common_Message_FieldEmpty_UserName {
            get {
                return ResourceManager.GetString("Common_Message_FieldEmpty_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password is too short..
        /// </summary>
        internal static string Common_Message_LengthShort_Password {
            get {
                return ResourceManager.GetString("Common_Message_LengthShort_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success!.
        /// </summary>
        internal static string Common_Message_Success {
            get {
                return ResourceManager.GetString("Common_Message_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It means the input area should be filled..
        /// </summary>
        internal static string Common_Tips_Register {
            get {
                return ResourceManager.GetString("Common_Tips_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email is already registered..
        /// </summary>
        internal static string Common_Valid_EmailExist {
            get {
                return ResourceManager.GetString("Common_Valid_EmailExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The username or the password is invalid..
        /// </summary>
        internal static string Common_Valid_Login {
            get {
                return ResourceManager.GetString("Common_Valid_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now you can chat with private questions..
        /// </summary>
        internal static string Common_Valid_Private {
            get {
                return ResourceManager.GetString("Common_Valid_Private", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some  is invalid..
        /// </summary>
        internal static string Common_Valid_Setting {
            get {
                return ResourceManager.GetString("Common_Valid_Setting", resourceCulture);
            }
        }
    }
}
