//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Message {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Message() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Message", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 請至少勾選一項選項.
        /// </summary>
        internal static string Checked_Null {
            get {
                return ResourceManager.GetString("Checked_Null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email or the password is invalid..
        /// </summary>
        internal static string Login_UserInvalid {
            get {
                return ResourceManager.GetString("Login_UserInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please activate your account in the email sent to you..
        /// </summary>
        internal static string Login_UserNotActivated {
            get {
                return ResourceManager.GetString("Login_UserNotActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新增失敗.
        /// </summary>
        internal static string MsgAddFailed {
            get {
                return ResourceManager.GetString("MsgAddFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新增成功.
        /// </summary>
        internal static string MsgAddSuccessfully {
            get {
                return ResourceManager.GetString("MsgAddSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 確認刪除?.
        /// </summary>
        internal static string MsgDeleteConfirm {
            get {
                return ResourceManager.GetString("MsgDeleteConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 刪除失敗.
        /// </summary>
        internal static string MsgDeleteFailed {
            get {
                return ResourceManager.GetString("MsgDeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;br/&gt;行為{0}已關聯到角色{1}.
        /// </summary>
        internal static string MsgDeleteFailedMessage {
            get {
                return ResourceManager.GetString("MsgDeleteFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 刪除失敗,當前行為已關聯到角色{0}.
        /// </summary>
        internal static string MsgDeleteFailedWithMessage {
            get {
                return ResourceManager.GetString("MsgDeleteFailedWithMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 刪除失敗:{0}.
        /// </summary>
        internal static string MsgDeleteFailedWithMessages {
            get {
                return ResourceManager.GetString("MsgDeleteFailedWithMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 刪除成功.
        /// </summary>
        internal static string MsgDeleteSuccessfully {
            get {
                return ResourceManager.GetString("MsgDeleteSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 修改失敗.
        /// </summary>
        internal static string MsgEditFailed {
            get {
                return ResourceManager.GetString("MsgEditFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 修改成功.
        /// </summary>
        internal static string MsgEditSuccessfully {
            get {
                return ResourceManager.GetString("MsgEditSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 不能为空.
        /// </summary>
        internal static string Null_Check {
            get {
                return ResourceManager.GetString("Null_Check", resourceCulture);
            }
        }
    }
}
